daily_fresh/apps/cart/urls.py
from django.urls import path
from .views import CartAddView,CartInfoView,CartUpdateView,DelCartView,CartDelView
app_name = 'cart'
urlpatterns = [
    path('add', CartAddView.as_view(), name='add'), # 添加购物车
    path('',CartInfoView.as_view(), name='show'),  # 显示购物车
    path('delete',DelCartView.as_view(), name='delete'),  # 显示购物车

    path('update',CartUpdateView.as_view(), name='update'),  # 显示购物车
    path('del',CartDelView.as_view(), name='del'),  # 显示购物车
]

daily_fresh/apps/goods/urls.py
from django.conf.urls import url
from django.urls import path
from .views import IndexView, DetailView, ListView
app_name = 'goods'
urlpatterns = [
    path('index', IndexView.as_view(), name='index') , # 为了做区分，nginx的调度
    path('goods/<int:goods_id>', DetailView.as_view(), name = 'detail'),
    path('list/<int:type_id>/<page>', ListView.as_view(), name='list'),
   # url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),

]

daily_fresh/apps/order/urls.py
from django.urls import path, include
from order.views import OrderPlaceView, OrderCommitView,\
    OrderPayView, CheckPayView, CommentView


app_name = 'order'
urlpatterns = [
    path('place', OrderPlaceView.as_view(), name='place'),
    path('commit', OrderCommitView.as_view(), name='commit'),  # 创建订单
    path('pay', OrderPayView.as_view(), name='pay'),  # 创建订单

    path('check', CheckPayView.as_view(), name='check'),  # 检查订单
    path('comment/<order_id>', CommentView.as_view(), name='comment')  # 检查订单

]

daily_fresh/apps/user/urls.py
from django.conf.urls import url
from django.urls import path
from . views import RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView, AddressView
from .views import log_out
from django.contrib.auth.decorators import login_required

app_name = 'user'
urlpatterns = [

    # url(r'^register$', views.register, name='register'),
    # url(r'^register_handle$', views.register_handle, name='register_handle')
    # url(r'^active/(?P<token>.*)$', views.ActiveView.as_view(), name='active'),

    url(r'^register$', RegisterView.as_view(), name='register'),
    path('active/<token>', ActiveView.as_view(), name='active'),
    # url(r'^login$', LoginView.as_view(), name='login'),
    path('login', LoginView.as_view(), name='login'),
    path('logout',log_out, name='logout'),
    path('', UserInfoView.as_view(), name='user'),
    path('order/<int:page>', UserOrderView.as_view(), name='order'),
    path('address', AddressView.as_view(), name='address'),

]

daily_fresh/daily_fresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 顺序也很重要
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('search/', include('haystack.urls')),  # 全文检索框架
    path('user/', include('user.urls', namespace='user')),  # 用户模块
    path('cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    path('order/', include('order.urls', namespace='order')),  # 订单模块
    path('', include('goods.urls', namespace='goods')),  # 商品模块
]

daily_fresh/apps/cart/models.py
from django.db import models

# Create your models here.

daily_fresh/apps/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.views.generic import View
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin
from goods.models import GoodsSKU


class CartAddView(View):
    """购物车记录添加"""

    def post(self, request):

        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        # noinspection PyBroadException
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值 -> hget cart_key 属性: cart_key[sku_id]
        # 如果sku_id在hash中不存在，hget返回None
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # redis中存在该商品，进行数量累加
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 设置hash中sku_id对应的值
        # hset ->如sku_id存在,更新数据,如sku_id不存在，追加数据
        conn.hset(cart_key, sku_id, count)

        # 获取用户购物车中的条目数
        cart_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'cart_count': cart_count, 'message': '添加成功'})


class CartInfoView(LoginRequiredMixin, View):
    '''购物车结算页面'''

    def get(self, request):
        # 登陆的用户
        user = request.user

        # 获取购物车中商品的信息
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 商品id  ：数量
        cart_dict = con.hgetall(cart_key)

        skus = []
        total_count = 0  # 总数目
        total_price = 0  # 总价格

        # 遍历这个字典
        for sku_id, count in cart_dict.items():
            # 根据id 获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算小计
            amount = sku.price * int(count)
            # 动态的位sku增加属性
            sku.amount = amount
            sku.count = int(count)
            skus.append(sku)
            total_count += int(count)
            total_price += amount

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_price': total_price,
        }
        return render(request, 'cart.html', context)


class CartUpdateView(View):
    '''响应前端发来的ajax请求，完成更新购物车的操作'''

    def post(self, request):
        '''购物车的操作就是对数据库cart—的操作，需要前端发来sku_id和count'''
        con = get_redis_connection('default')
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据 得到的就是一种商品的值，每次改变数量都会向这里来发送请求，走的是次数，而不是量
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        # noinspection PyBroadException
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 更新数据库
        cart_key = 'cart_%d' % user.id
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品数量不足'})
        con.hset(cart_key, sku_id, count)

        # 计算商品的总数
        total_count = 0
        vals = con.hvals(cart_key)  # 将cart_key中的value作为列表返回，相当于dic.values()
        for val in vals:
            total_count += int(val)  # 所有的value值加起来就是商品的总件数。
        # 返回应答
        return JsonResponse({'res': 5, 'message': '更新成功', 'total_count': total_count})
        # 这个


class DelCartView(View):
    def get(self, request):
        con = get_redis_connection('default')
        user = request.user
        cart_key = 'cart_%d' % user.id

        total_count = 0
        try:
            con.delete(cart_key)
            return render(request, 'cart.html', {'total_count': total_count})
        except:
            return render(request, 'cart.html', {'total_count': total_count})


class CartDelView(View):
    '''购物车记录的删除'''

    def post(self, request):
        # 判断用户是否登陆
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接受参数
        sku_id = request.POST.get('sku_id')
        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})
        # 商品是否存在

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': 's商品不存在'})
        # 删除购物车记录
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        con.hdel(cart_key, sku_id)
        return JsonResponse({'res': 3, 'message': '删除成功'})

daily_fresh/templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

    <title>{% block title %}
    {% endblock %}</title>

    <link rel="stylesheet" type="text/css" href={% static "css/reset.css" %}>
    <link rel="stylesheet" type="text/css" href={% static "css/main.css" %}>
    {% block topfiles %}

    {% endblock %}
</head>
<body>
{% block header_con %}
    {#    顶部信息#}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎你：{{ user.username }}
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">注销</a>
                    </div>


                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}

                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' 1 %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block serch_bar %}
    {#    搜索模块 #}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static  'images/logo.png' %}"></a>
        <div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="button" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
{% endblock %}



{% block body %}

{% endblock %}


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="https://www.jianshu.com/u/965f9c86a45b">友情链接</a>
    </div>
    <p></p>
    <p>电话：15684175367 鲁ICP备19030032号-1 </p>
</div>
{% block bottom %}
    {#    底部html元素 #}
{% endblock %}

{% block bottom_files %}
    {#   底部JS#}
{% endblock %}

</body>
</html>

daily_fresh/templates/base_no_cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block serch_bar %}
    {#    搜索模块 #}
    <div class="search_bar clearfix">
        <a href="index_2.html" class="logo fl"><img src={% static "images/logo.png" %}></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}

        {% endblock %}</div>
        <div class="search_con fr">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="button" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
    </div>
{% endblock %}

daily_fresh/templates/base_user_center.html
{#用户中心的父模板，只需要重写right_content块#}

{% extends 'base_no_cart.html' %}

{% block title %}
    天天生鲜用户中心
{% endblock %}

{% block page_title %}
    用户中心
{% endblock %}

{% block body %}
    <div class="main_con clearfix">
        {# 左侧内容一样#}
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}" {% if page == 'user' %} class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %} class="active"{% endif %}>· 全部订单</a>
                </li>
                <li><a href="{% url 'user:address' %}" {% if page == 'address' %} class="active"{% endif %}>· 收货地址</a>
                </li>
            </ul>
        </div>
        {# 用户中心-右侧内容块 #}
        {% block right_content %}

        {% endblock right_content %}
    </div>
{% endblock %}

daily_fresh/templates/cart.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-购物车{% endblock title %}
{% block page_title %}购物车{% endblock page_title %}

{% block body %}
	<div class="total_count">全部商品<em>{{ total_count }}</em>件
    </div>
    <div  class="total_count"><a href="{% url 'cart:delete' %}" style="position: center"><b>清空购物车</b></a>
    </div>
    {% csrf_token %}
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>


    <form method="post" action="{% url 'order:place' %}">
    {% csrf_token%}
    {% for sku in skus %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="sku_ids"  value="{{ sku.id }}"></li>
		<li class="col02"><img src="{{ sku.image.url }}"></li>
		<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">{{ sku.amount }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}
	<ul class="settlements">
		<li class="col01"><input type="checkbox" name=""></li>
		<li class="col02">全选 / 全不选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock body %}

{# 开始编写jq代码#}
{% block bottom_files %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
    update_page_info()
    // 计算被选中的商品的总件数和总价格
    function update_page_info() {
        var total_count = 0
        var total_price = 0
        // 获取所有被选中的商品的ul元素
        $('.cart_list_td').find(':checked').parents('ul').each(function () {
            // 获取商品的数目和小计
            count = $(this).find('.num_show').val()
            amount = $(this).children('.col07').text()
            // 累加计算商品的总件数和总金额
            total_count += parseInt(count)
            total_price += parseFloat(amount)
        })
        // 设置选中商品的总件数和总金额
        $('.settlements').find('em').text(total_price.toFixed(2))
        $('.settlements').find('b').text(total_count)
    }



    // 全选和全不选
    $('.settlements').find(':checkbox').change(function () {
        // 获取全选checkbox的选中状态
        var is_checked = $(this).prop('checked')
        // 设置商品的checkbox和全选的checkbox状态保持一致
        $('.cart_list_td').find(':checkbox').each(function () {
            $(this).prop('checked', is_checked)
        })
        // 更新页面信息
        update_page_info()
    })

    //全选按钮的check属性变动
    $('.cart_list_td').find(':checkbox').change(function () {
        // 当商品的checkbox变化，判断全选是否应该被选中
        len_checked = $('.cart_list_td').find(':checked').length
        len_checkbox =  $('.cart_list_td').find(':checkbox').length
        if (len_checked<len_checkbox){
            is_checked = false
        } else{
            is_checked = true
        }
        $('.settlements').find(':checkbox').prop('checked',is_checked)
        update_page_info()
    })
//////////////////////////////////////////////////////////////////////////////////////
   //计算商品的小计
    function update_goods_amount(sku_ul){
        //获取商品的价格和数量
        count = sku_ul.find('.num_show').val()
        price = sku_ul.children('.col05').text()

        amount = parseInt(count)*parseFloat(price)
        //设置商品的小计
        sku_ul.children('.col07').text(amount.toFixed(2)+"元")
    }

    //更新购物车的记录
    $('.add').click(function () {
        //获取商品的id和数量，post给view
        count = $(this).next().val()
        sku_id = $(this).next().attr('sku_id')
        count = parseInt(count) + 1
        csrf  =$('input[name="csrfmiddlewaretoken"]').val()
        params = {'sku_id':sku_id,'count':count,'csrfmiddlewaretoken':csrf}
        error_update = false

        $.ajaxSettings.async = false;
        $.post(
            '/cart/update',
            params,
            function (data) {
                if (data.res == 5) {
                    //更新成功
                    error_update  =false
                    //更新全部商品的总
                    $('.total_count em').text(data.total_count)

                }else{
                    //失败
                    error_update =true
                    alert(data.errmsg)
                }
            }
        )
        if(error_update==false){
            //重新设置商品的数目
            $(this).next().val(count)
            //小计
            update_goods_amount($(this).parents('ul'))
            update_page_info()
        }
        else{
            count = count-1
            $(this).next().val(count)
            update_goods_amount($(this).parents('ul'))
            update_page_info()
        }

    })
    $('.minus').click(function () {
        //获取商品的id和数量，post给view
        count = $(this).prev().val()
        sku_id = $(this).prev().attr('sku_id')
        count = parseInt(count) - 1
        if(count<=0){
            return
        }
        csrf  =$('input[name="csrfmiddlewaretoken"]').val()
        params = {'sku_id':sku_id,'count':count,'csrfmiddlewaretoken':csrf}
        error_update = false

        $.ajaxSettings.async = false;
        $.post(
            '/cart/update',params,function (data) {
                if (data.res == 5) {
                    //更新成功
                    error_update  =false
                    //更新全部商品的总
                    $('.total_count em').text(data.total_count)

                }else{
                    //失败
                    error_update =true
                    alert(data.errmsg)
                }
            }
        )
        if(error_update==false){
            //重新设置商品的数目
            $(this).prev().val(count)
            //小计
            update_goods_amount($(this).parents('ul'))
            update_page_info()
        }
        else{
            $(this).prev().val(count)
            update_goods_amount($(this).parents('ul'))
            update_page_info()
        }

    })

    //记录用户输入之前商品的数量
    $('.num_show').focus(function () {
        pre_count = $(this).val()
    })
    $('.num_show').blur(function () {
        //获取商品的id和数量，post给view
        count = $(this).val()
        sku_id = $(this).attr('sku_id')
        if(isNaN(count) || count.trim().length==0||parseInt(count)<=0){
            //让设置无效化，为之前的值
            alert("你设置的数值不合理")
            $(this).val(pre_count)
            return
        }

        count = parseInt(count)
        csrf  =$('input[name="csrfmiddlewaretoken"]').val()
        params = {'sku_id':sku_id,'count':count,'csrfmiddlewaretoken':csrf}
        error_update = false
        $.ajaxSettings.async = false;
        $.post(
            '/cart/update',params,function (data) {
                if (data.res == 5) {
                    //更新成功
                    error_update  =false
                    //更新全部商品的总
                    $('.total_count em').text(data.total_count)

                }else{
                    //失败
                    error_update =true
                    $('.total_count em').text(data.total_count)
                    alert(data.errmsg)
                }
            }
        )
        if(error_update==false){
            //重新设置商品的数目
            $(this).val(count)
            //小计
            update_goods_amount($(this).parents('ul'))
            update_page_info()
        }
        else{
            $(this).val(pre_count)
            update_goods_amount($(this).parents('ul'))
            update_page_info()
        }

    })
    ////////////////////////
    //删除商品
    $('.cart_list_td').children('.col08').children('a').click(function () {
        //获取对应商品的id
        sku_id = $(this).parents('ul').find('.num_show').attr('sku_id')
        csrf  =$('input[name="csrfmiddlewaretoken"]').val()
        params={'sku_id':sku_id, 'csrfmiddlewaretoken':csrf}
       //获取要删除的ul
        sku_ul = $(this).parents('ul')
        $.post(
            '/cart/del',
            params,
            function (data) {
                if (data.res == 3){
                    //删除成功
                    //移除ul元素
                    sku_ul.remove()
                    //
                    update_page_info()
                }
                else {
                    alert(data.errmsg)
                }

            }
        )
    })
    </script>
{% endblock bottom_files %}

daily_fresh/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    天天生鲜 · 首页
{% endblock %}


{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            {% for type in types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">

                {% for goods_banner in goods_banners %}
                    <li><a href="{% url 'goods:detail' goods_banner.sku.id %}"><img src="{{ goods_banner.image.url }}"
                                                                                    alt="幻灯片"></a></li>
                {% endfor %}

            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            {% for promotion_banner in promotion_banners %}
                <a href="{{ promotion_banner.url }}"><img src="{{ promotion_banner.image.url }}"></a>

            {% endfor %}


        </div>
    </div>

    {% for type in types %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for title_banner in type.title_banners %}
                        <a href="{% url 'goods:detail' title_banner.sku.id %}">{{ title_banner.sku.name }}</a>
                    {% endfor %}


                </div>
                <a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img
                        src="{{ type.image.url }}"></div>
                <ul class="goods_list fl">
                    {% for image_banner in type.image_banners %}

                        <li>
                            <h4><a href="{% url 'goods:detail' image_banner.sku.id %}">{{ image_banner.sku.name }}</a>
                            </h4>
                            <a href="{% url 'goods:detail' image_banner.sku.id %}"><img
                                    src="{{ image_banner.sku.image.url }}"></a>
                            <div class="prize">¥ {{ image_banner.sku.price }}</div>
                        </li>


                    {% endfor %}

                </ul>
            </div>
        </div>
    {% endfor %}


{% endblock %}

daily_fresh/templates/static_base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    
    <title>{% block title %}
	{% endblock %}</title>

	<link rel="stylesheet" type="text/css" href={% static "css/reset.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "css/main.css" %}>

    {% block topfiles %}

    {% endblock %}
</head>
<body>
{% block header_con %}
{#    顶部信息#}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                    <div class="login_btn fl">
					    <a href="{% url 'user:login' %}">登录</a>
					    <span>|</span>
					    <a href="{% url 'user:register' %}">注册</a>
				    </div>

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}


{% block serch_bar %}
{#    搜索模块 #}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock %}



{% block body %}

{% endblock %}


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 该网站纯粹为了学习使用，不包含任何的盈利行为</p>
		<p>电话：15684175367    鲁ICP备19030032号-1	</p>
	</div>
    {% block bottom %}
{#    底部html元素 #}
    {% endblock %}
    
    {% block bottom_files %}
{#   底部JS#}
    {% endblock %}
	
</body>
</html>